from musicsort.gui.widgets.dashboard_view import DashboardView
from musicsort.gui.widgets.scan_view import ScanView
from musicsort.gui.widgets.csv_view import CSVView
from musicsort.gui.widgets.preview_view import PreviewView
from musicsort.gui.widgets.duplicate_view import DuplicateView
from musicsort.gui.widgets.restore_view import RestoreView
from musicsort.gui.widgets.settings_view import SettingsView
from musicsort.gui.widgets.console_view import ConsoleView
from musicsort.gui.widgets.library_view import LibraryView
from musicsort.gui.widgets.categories_view import CategoriesView
